# Generated by Django 5.0 on 2023-12-15 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='submit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.IntegerField()),
                ('repassword', models.IntegerField()),
                ('person_select', models.CharField(max_length=20)),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('fgender', models.CharField(max_length=20)),
                ('religion', models.CharField(max_length=30)),
                ('language', models.CharField(max_length=20)),
            ],
        ),
    ]
